language: node_js
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - clang-3.9
      - build-essential

env:
  global:
    - CC=clang
    - CXX=clang++

cache:
  directories:
    - ~/.npm

node_js:
  - 8
  - 10

notifications:
  email: false

branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/

after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
